# name: Build and Deploy Robot Shop

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     name: Build and Push ${{ matrix.service }} Image
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         service: [user, cart, web, catalogue, dispatch, payment, shipping]
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Log in to Docker Registry
#         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

#       - name: Build and Push Image
#         run: |
#           docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest ./${{ matrix.service }}
#           docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest

#   deploy:
#     name: Deploy to AKS
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Azure Login
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - name: Set AKS Context
#         run: |
#           az aks get-credentials \
#             --resource-group ecommerce-demo \
#             --name three-tier \
#             --overwrite-existing

#       - name: Create Namespace if Not Exists
#         run: |
#           kubectl get ns robot-shop || kubectl create ns robot-shop

#       - name: Add Ingress-NGINX Helm Repo
#         run: |
#           helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
#           helm repo update

#       - name: Install Ingress-NGINX
#         run: |
#           kubectl create namespace ingress-nginx --dry-run=client -o yaml | kubectl apply -f -
#           helm upgrade ingress-nginx ingress-nginx/ingress-nginx \
#             --install \
#             --namespace ingress-nginx
        
#       - name: Deploy Robot Shop with Helm
#         run: |
#           helm upgrade robot-shop ./helm \
#             --install \
#             --namespace robot-shop \
#             --values AKS/helm/values.yaml

      ### - name: Apply Robot Shop Ingress
      #   run: kubectl apply -f helm/robot-shop-ingress.yaml


  name: Build and Deploy Robot Shop
  on:
    push:
      branches:
       - main
    workflow_dispatch:

  jobs:
    build:
      name: Build and Push ${{ matrix.service }} Image
      runs-on: ubuntu-latest
      strategy:
      matrix:
        service: [user, cart, web, catalogue, dispatch, payment, shipping]
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Azure Login
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Azure ACR Login
          run: |
            az acr login --name ${{ secrets.ACR_LOGIN_SERVER }}

        - name: Build and Push Image to ACR
          run: |
            IMAGE=${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.service }}:latest
            docker build -t $IMAGE ./${{ matrix.service }}
            docker push $IMAGE

    deploy:
      name: Deploy to AKS
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Azure Login
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Set AKS Context
          run: |
            az aks get-credentials \
              --resource-group ecommerce-demo \
              --name three-tier \
              --overwrite-existing

        - name: Create Namespace if Not Exists
          run: |
            kubectl get ns robot-shop || kubectl create ns robot-shop

        - name: Add Ingress-NGINX Helm Repo
          run: |
            helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
            helm repo update

        - name: Install Ingress-NGINX
          run: |
            kubectl create namespace ingress-nginx --dry-run=client -o yaml | kubectl apply -f -
            helm upgrade ingress-nginx ingress-nginx/ingress-nginx \
              --install \
              --namespace ingress-nginx
        
        - name: Deploy Robot Shop with Helm
          run: |
            helm upgrade robot-shop ./helm \
              --install \
              --namespace robot-shop \
              --values AKS/helm/values.yaml
              --set image.repo=${{ secrets.ACR_LOGIN_SERVER }} \
              --set image.version=latest